//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Permission.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Esmart.Permission.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td bgcolor=&quot;#f2f2f2&quot;&gt;
        ///            &lt;table width=&quot;600&quot; border=&quot;0&quot; align=&quot;center&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;margin:30px auto;padding:20px;&quot; bgcolor=&quot;#FFFFFF&quot;&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td colspan=&quot;2&quot; style=&quot;	border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #CCC;&quot;&gt;
        ///                        &lt;div style=&quot;width:90%;margin:auto;&quot;&gt;
        ///                            &lt;div style=&quot;float:l [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UserPasswordReseted {
            get {
                return ResourceManager.GetString("UserPasswordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td bgcolor=&quot;#f2f2f2&quot;&gt;
        ///            &lt;table width=&quot;600&quot; border=&quot;0&quot; align=&quot;center&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;margin:30px auto;padding:20px;&quot; bgcolor=&quot;#FFFFFF&quot;&gt;
        ///                &lt;!--&lt;tr&gt;
        ///                    &lt;td colspan=&quot;2&quot; style=&quot;border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #CCC;&quot;&gt;&lt;img src=&quot;http://www.suidao.in/public/images/logo_blue.png&quot;&gt;&lt;/td&gt;
        ///                &lt;/tr&gt;--&gt;
        ///                [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UserRegisterMail {
            get {
                return ResourceManager.GetString("UserRegisterMail", resourceCulture);
            }
        }
    }
}
